<?php


namespace frontend\controllers;


use yii\web\Controller;

class MainController extends Controller
{
    public function actions()
    {
        return [
            'error' => [
                'class' => \yii\web\ErrorAction::class,
            ],
        ];
    }

    public function init()
    {
        $this->view->title = 'Феспо';
        parent::init(); // TODO: Change the autogenerated stub
    }
}