<?php


namespace frontend\controllers;


use common\models\Orders;
use Yii;
use yii\web\Controller;

class MainController extends Controller
{
    public function actions()
    {
        return [
            'error' => [
                'class' => \yii\web\ErrorAction::class,
            ],
        ];
    }

    public function init()
    {
        $this->view->title = 'Феспо';
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function actionSaveForm()
    {
        $model = new Orders();

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->save()) {

            } else {
               $model->errors;
            }
        }

//        return $this->redirect(Yii::$app->request->referrer);
    }
}